services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dbtickets
    ports:
      - "5432:5432"
    restart: always

networks:
  default:
    name: local-network
    external: true